import { SESSION_MODULES } from "@/domains/cbt-modules/constants/modules";

export const CORE_MODULES = {
  BEHAVIORAL_ACTIVATION: SESSION_MODULES.BEHAVIORAL_ACTIVATION,
  BEHAVIORAL: SESSION_MODULES.BEHAVIORAL,
  COGNITIVE: SESSION_MODULES.COGNITIVE,
  CORE_BELIEFS: SESSION_MODULES.CORE_BELIEFS,
  CRISIS: SESSION_MODULES.CRISIS,
  CURIOSITY: SESSION_MODULES.CURIOSITY,
  MINDFULNESS: SESSION_MODULES.MINDFULNESS,
  REFRAMING: SESSION_MODULES.REFRAMING,
  SHOULDS: SESSION_MODULES.SHOULDS,
  VALUES_CLARIFICATION: SESSION_MODULES.VALUES_CLARIFICATION,
} as const;
export const PROCESS_MODULES = {
  OVERWHELM: SESSION_MODULES.OVERWHELM,
  RESISTANCE_OVERWHELM: SESSION_MODULES.RESISTANCE_OVERWHELM,
  RESISTANCE_PUSHBACK: SESSION_MODULES.RESISTANCE_PUSHBACK,
  VALIDATE: SESSION_MODULES.VALIDATE,
} as const;
export const UTILITY_MODULES = {
  BEHAVIORAL: SESSION_MODULES.BEHAVIORAL,
  FIRST_TIME: SESSION_MODULES.FIRST_TIME,
  GUIDANCE: SESSION_MODULES.GUIDANCE,
  PATTERN_WHY: SESSION_MODULES.PATTERN_WHY,
  PATTERN: SESSION_MODULES.PATTERN,
  PSYCHOEDUCATION: SESSION_MODULES.PSYCHOEDUCATION,
} as const;
